title: Drew Dickenson
email: macy.dickenson@howard.edu
baseurl: "" # Leave empty for user/organization site
url: "https://dickensondrew.github.io"
timezone: America/New_York

# Jekyll configuration
markdown: kramdown
permalink: pretty

# Directories
includes_dir: _includes
layouts_dir: _layouts
collections_dir: _collections
data_dir: _data

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

github_metadata: false
# Theme and appearance
theme: minima
minima:
  skin: classic

# Navigation bar links
header_pages:
  - teaching.md
  - math-159.md
  - math-007.md
  - math-005.md
  - math-181.md

# Custom collections
collections:
  courses:
    output: true
    permalink: /courses/:path/

# SASS
sass:
  sass_dir: assets/css
  style: compressed

# Files/directories to exclude from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .jekyll-cache
  - .sass-cache
  - README.md

# Files/directories to include in the build
include:
  - _pages
  - assets/css/master.css
  - images

# Default front matter for collections
defaults:
  - scope:
      path: ""
      type: "courses"
    values:
      layout: "course"
      toc: true
